AllCops:
  TargetRubyVersion: 3.1
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*.gemfile'
    - 'gemfiles/vendor/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'

Documentation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SingleLineMethods:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'Appraisals'
