name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 10 * * *"

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
        gemfile: ["gemfiles/rails_6_0.gemfile", "gemfiles/rails_6_1.gemfile"]

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      COVERALLS: true

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Collect coverage info
      run: bundle exec rake spec
      
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      continue-on-error: true
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.ruby }}-${{ matrix.gemfile }}
        parallel: true


  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
    - name: Send to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
