name: Memory Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 10 * * *"

jobs:
  bench:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
        gemfile: ["gemfiles/rails_6_0.gemfile"]

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run bench
      run: bundle exec rake memory
